import { LANG } from "../../i18n/runtime";

const COPY = {
  en: {
    invalid: "The response does not contain a valid provenance record.",
    failed: "Could not read this record: {0}",
    retry: "Retry reading",
    noCode: "No producing code is included in this record.",
    codeElsewhere: "The producing Cell is recorded, but its source is not included in this view.",
    inputs: "Recorded inputs",
    noInputs: "No inputs were recorded. This does not establish that there were no dependencies.",
    noLineage: "No lineage was recorded for this version.",
    otherNotebook: "This artifact belongs to another session. Its recorded source is available in Code and Review.",
    unknownSession: "The owning session is not available in this view.",
    unknownEnvironment: "Not recorded",
    packages: "Recorded packages",
    evidenceScope:
      "Checks the version record, the recorded sha256, that the snapshot file exists and matches the recorded size, and that the producer is this sub-agent with a successful Cell. The content hash is not recomputed. This is not a scientific conclusion or a claim of statistical validity.",
    evidenceSummary: "Version and producer checked {0} · Insufficient evidence {1}",
    evidenceUnavailable: "Evidence unavailable",
    evidenceTruncated: "Showing the first 12 of {0}",
    evidenceDetails: "Check details",
    evidenceVerified: "Version and producer checked",
    evidenceInsufficient: "Insufficient evidence",
    evidenceNoChecksum: "no sha256",
    evidenceCell: "Cell {0}",
    evidenceNoCell: "no Cell status",
    evidenceReasonOtherFrame: "Version belongs to another sub-agent",
    evidenceReasonNoChecksum: "No sha256 record",
    evidenceReasonNoSnapshot: "No snapshot path",
    evidenceReasonSnapshotMissing: "Snapshot file is missing",
    evidenceReasonSizeMismatch: "Snapshot size does not match the record",
    evidenceReasonCellNotRecorded: "Producing Cell was not recorded",
    evidenceReasonCellFailed: "Producing Cell did not succeed",
    evidenceReasonCellOtherFrame: "Producing Cell belongs to another sub-agent",
    evidenceReasonNoCellReceipt: "No Cell receipt (native write)",
  },
  zh: {
    invalid: "响应未包含有效的溯源记录。",
    failed: "无法读取此记录：{0}",
    retry: "重试读取",
    noCode: "此记录未包含生产代码。",
    codeElsewhere: "已记录生产此版本的 Cell，但此面板未包含其源码。",
    inputs: "已记录输入",
    noInputs: "未记录输入。这不能证明没有依赖。",
    noLineage: "此版本未记录溯源信息。",
    otherNotebook: "此产物属于其他会话。可在代码和审查中查看已记录来源。",
    unknownSession: "此视图未包含所属会话信息。",
    unknownEnvironment: "未记录",
    packages: "已记录的包",
    evidenceScope:
      "仅核对版本记录、sha256 记录、快照文件存在与大小、生产者为该子代理及其 Cell 成功；未重新计算内容哈希；不代表科学结论或统计有效性。",
    evidenceSummary: "版本与归属已核对 {0} · 证据不足 {1}",
    evidenceUnavailable: "证据不可用",
    evidenceTruncated: "仅显示前 12 项 / 共 {0} 项",
    evidenceDetails: "核对明细",
    evidenceVerified: "版本与归属已核对",
    evidenceInsufficient: "证据不足",
    evidenceNoChecksum: "无 sha256",
    evidenceCell: "Cell {0}",
    evidenceNoCell: "无 Cell 状态",
    evidenceReasonOtherFrame: "版本不属于该子代理",
    evidenceReasonNoChecksum: "无 sha256 记录",
    evidenceReasonNoSnapshot: "无快照路径",
    evidenceReasonSnapshotMissing: "快照文件不存在",
    evidenceReasonSizeMismatch: "快照大小与记录不符",
    evidenceReasonCellNotRecorded: "未找到生产 Cell 记录",
    evidenceReasonCellFailed: "生产 Cell 未成功",
    evidenceReasonCellOtherFrame: "生产 Cell 属于其他子代理",
    evidenceReasonNoCellReceipt: "无 Cell 回执（原生写入）",
  },
};

export function provenanceT(key: keyof typeof COPY.en, ...args: unknown[]): string {
  return COPY[LANG === "zh" ? "zh" : "en"][key].replace(/\{(\d+)\}/g, (_, n: string) => String(args[Number(n)] ?? ""));
}
